logger:
  development: ${RUMORS_LOGGER_DEVELOPMENT}
  add_source: ${RUMORS_LOGGER_ADD_SOURCE}
  level: ${RUMORS_LOGGER_LEVEL}
  encoding: ${RUMORS_LOGGER_ENCODING}
  output_paths:
    - ${RUMORS_LOGGER_OUTPUT_PATH}

mongo:
  ping: ${RUMORS_MONGO_PING}
  uri: ${RUMORS_MONGO_URI}

redis:
  ping: ${RUMORS_REDIS_PING}
  username: ${RUMORS_REDIS_USERNAME}
  password: ${RUMORS_REDIS_PASSWORD}
  addrs:
    - ${RUMORS_REDIS_ADDRESS}

http:
  address: ${RUMORS_HTTP_ADDRESS}
  cert_file: ${RUMORS_HTTP_CERT_FILE}
  key_file: ${RUMORS_HTTP_KEY_FILE}
  graceful_timeout: 5s
  jwt:
    private_key: ${RUMORS_JWT_PRIVATE_KEY}
    access_token_ttl: ${RUMORS_JWT_ACCESS_TOKEN_TTL}
    refresh_token_ttl: ${RUMORS_JWT_REFRESH_TOKEN_TTL}
  middleware:
    metrics:
      exclude_endpoint: "^/(metrics|favicon.ico)"
    compress: { }
    cors:
      allowed_origin: ${RUMORS_CORS_ALLOWED_ORIGIN}
      allowed_headers: ${RUMORS_CORS_ALLOWED_HEADERS}
      allowed_methods: ${RUMORS_CORS_ALLOWED_METHODS}
      allow_credentials: ${RUMORS_CORS_ALLOW_CREDENTIALS}
      exposed_headers: ${RUMORS_CORS_EXPOSED_HEADERS}
      max_age: ${RUMORS_CORS_MAX_AGE}

task:
  scheduler:
    sync_interval: ${RUMORS_SCHEDULER_SYNC_INTERVAL}
  server:
    queues:
      tgmember: 9
      tgcmd: 7
      broadcast: 8

telegram:
  token: ${RUMORS_TELEGRAM_TOKEN}
  owner: ${RUMORS_TELEGRAM_OWNER}
  retry: ${RUMORS_TELEGRAM_RETRY}
  poller:
    only_owner: true
    buffer: 50
    limit: 50
    allowed_updates:
      - "message"
      - "edited_message"
      - "channel_post"
      - "edited_channel_post"
      - "my_chat_member"
      - "chat_member"