version: "3.8"

services:
  rumors:
    build:
      context: .
    environment:
      - RUMORS_ENDURE_LOG_LEVEL=${RUMORS_ENDURE_LOG_LEVEL:-info}
      - RUMORS_LOG_LEVEL=${RUMORS_LOG_LEVEL:-info}
      - RUMORS_TASK_LOG_LEVEL=${RUMORS_TASK_LOG_LEVEL:-info}
      - RUMORS_PUBSUB_LOG_LEVEL=${RUMORS_PUBSUB_LOG_LEVEL:-info}
      - RUMORS_HTTP_LOG_LEVEL=${RUMORS_HTTP_LOG_LEVEL:-info}
      - RUMORS_TELEGRAM_LOG_LEVEL=${RUMORS_TELEGRAM_LOG_LEVEL:-info}
      - RUMORS_LOG_ENCODING=${RUMORS_LOG_ENCODING:-json}
      - RUMORS_HTTP_LOG_ENCODING=${RUMORS_HTTP_LOG_ENCODING:-json}
      - RUMORS_TELEGRAM_LOG_ENCODING=${RUMORS_TELEGRAM_LOG_ENCODING:-json}
      - RUMORS_TASK_LOG_ENCODING=${RUMORS_TASK_LOG_ENCODING:-json}
      - RUMORS_PUBSUB_LOG_ENCODING=${RUMORS_PUBSUB_LOG_ENCODING:-json}
      - RUMORS_REDIS_ADDRESS=${RUMORS_REDIS_ADDRESS:-redis:6379}
      - RUMORS_REDIS_PING=${RUMORS_REDIS_PING:-true}
      - RUMORS_HTTP_ADDRESS=0.0.0.0:443
      - RUMORS_HTTP_CERT_PATH=/
      - RUMORS_HTTP_CERT_FILE=cert.pem
      - RUMORS_HTTP_KEY_FILE=key.pem
      - RUMORS_HTTP_SWAGGER_ENABLED=${RUMORS_HTTP_SWAGGER_ENABLED:-true}
      - RUMORS_HTTP_JWT_ACCESS_TOKEN_TTL=${RUMORS_HTTP_JWT_ACCESS_TOKEN_TTL:-3m}
      - RUMORS_HTTP_JWT_REFRESH_TOKEN_TTL=${RUMORS_HTTP_JWT_REFRESH_TOKEN_TTL:-24h}
      - RUMORS_HTTP_JWT_PRIVATE_KEY=/rsa_key.pem
      - RUMORS_HTTP_MDWR_CORS_ALLOWED_ORIGIN=${RUMORS_HTTP_MDWR_CORS_ALLOWED_ORIGIN:-*}
      - RUMORS_HTTP_UI_FRONT=${RUMORS_HTTP_UI_FRONT:-}
      - RUMORS_HTTP_UI_SYS=${RUMORS_HTTP_UI_SYS:-}
      - RUMORS_MONGO_URI=${RUMORS_MONGO_URI:-mongodb://rumors:rumors@mongo:27017/rumors?authsource=admin}
      - RUMORS_MONGO_PING=${RUMORS_MONGO_PING:-true}
      - RUMORS_TELEGRAM_TOKEN=${RUMORS_TELEGRAM_TOKEN}
      - RUMORS_TELEGRAM_OWNER=${RUMORS_TELEGRAM_OWNER}
      - RUMORS_TELEGRAM_RETRY=${RUMORS_TELEGRAM_RETRY:-3}
      - RUMORS_TASK_SCHEDULER_SYNC_INTERVAL=${RUMORS_TASK_SCHEDULER_SYNC_INTERVAL:-15m}
    ports:
      - ${RUMORS_HTTP_ADDRESS:-127.0.0.1:8443}:443
    volumes:
      - ${RUMORS_HTTP_CERT_FILE}:/cert.pem
      - ${RUMORS_HTTP_KEY_FILE}:/key.pem
      - ${RUMORS_HTTP_JWT_PRIVATE_KEY}:/rsa_key.pem
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7.0-alpine
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-rumors}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-rumors}
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: