basePath: /api/v1
definitions:
  entity.Feed:
    properties:
      created_at:
        type: string
      enabled:
        type: boolean
      host:
        type: string
      id:
        type: string
      languages:
        items:
          type: string
        type: array
      link:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  entity.Source:
    enum:
    - feed
    type: string
    x-enum-varnames:
    - FeedSource
  pubsub.Article:
    properties:
      categories:
        items:
          type: string
        type: array
      id:
        type: string
      lang:
        type: string
      link:
        type: string
      long_desc:
        type: string
      pub_date:
        type: string
      short_desc:
        type: string
      source:
        $ref: '#/definitions/entity.Source'
      source_id:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  wool.Error:
    properties:
      code:
        type: integer
      data: {}
      developer_message:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  title: Rumors Frontend API
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: get articles
      parameters:
      - default: 0
        description: Page Index
        in: query
        minimum: 0
        name: index
        type: integer
      - default: 20
        description: Page Size
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      - description: Source Host
        in: query
        name: host
        type: string
      - description: Source IDs
        in: query
        name: source_id
        type: string
      - description: Languages
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pubsub.Article'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wool.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wool.Error'
      summary: List articles
      tags:
      - articles
  /feeds:
    get:
      consumes:
      - application/json
      description: get feeds
      parameters:
      - default: 0
        description: Page Index
        in: query
        minimum: 0
        name: index
        type: integer
      - default: 20
        description: Page Size
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Feed'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wool.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wool.Error'
      summary: List feeds
      tags:
      - feeds
  /realtime:
    get:
      description: sse stream
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wool.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wool.Error'
        default:
          description: ""
      summary: Realtime
      tags:
      - sse
swagger: "2.0"
