name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Rumors
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: app

    - name: Checkout system dashboard UI
      uses: actions/checkout@v3
      with:
        repository: rumorsflow/sys-ui
        ref: main
        token: ${{ secrets.GH_PAT }}
        path: sys-ui

    - name: Checkout front UI
      uses: actions/checkout@v3
      with:
        repository: rumorsflow/ui
        ref: main
        path: ui

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'

    - name: Build system dashboard UI
      working-directory: ./sys-ui
      run: |
        npm ci
        go mod tidy
        BASE_URL=/sys VITE_APP_API_URL=/sys/api go run . -dst ../app/internal/http/sys/ui

    - name: Build front UI
      working-directory: ./ui
      run: |
        npm ci
        VITE_APP_NAME_CAPTION=ALPHA npm run build -- --outDir ../app/internal/http/front/ui

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        workdir: app
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}